name: Deployment
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ce-cloud
    if: github.event_name == 'push'
    steps:
      - name: Clone Repo 🤖
        uses: actions/checkout@v3

      - name: Set Environment Variables 🔠
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          REDISHOST: ${{ secrets.REDISHOST }}
          JWT_SECRET: ${{ secrets.JWT_SECRET_CE_CLOUD }}
        run: |
          echo "BACKEND_URL=$BACKEND_URL" >> .env
          echo "REDISHOST=$REDISHOST" >> .env
          echo "JWT_SECRET=$JWT_SECRET" >> .env

      - name: Clear Cache 🫧
        run: |
          docker stop real-time || true
          docker rm real-time || true
          docker rmi real-time-real-time:latest || true

      - name: Run Image ✅
        run: |
          docker compose -f docker-compose.ce-cloud.yaml up -d

      - name: Message ✉️
        uses: fjogeleit/http-request-action@v1
        with:
          timeout: 60000
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"content": "CE PROJECT Real Time CE Cloud ✅","embeds": [{"title": "Real Time URL","description": "https://ce67-07.cloud.ce.kmitl.ac.th/realtime"}]}'
